# Generated by Django 5.0.7 on 2024-07-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='palabrabaneada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100, unique=True, verbose_name='Palabra prohibida')),
            ],
            options={
                'db_table': 'ban',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.TextField(unique=True, verbose_name='Pregunta')),
                ('respuesta', models.TextField()),
            ],
            options={
                'db_table': 'preguntas',
                'managed': False,
            },
        ),
    ]
